# Generated by Django 2.1.5 on 2019-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('cork_area', models.CharField(max_length=255)),
                ('dublin_area', models.CharField(max_length=255)),
                ('limerick_area', models.CharField(max_length=255)),
                ('galway_area', models.CharField(max_length=255)),
                ('waterford_area', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
