# Generated by Django 2.1.5 on 2019-12-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191217_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyModel',
        ),
    ]
