# Generated by Django 2.1.7 on 2019-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_myskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataskill', models.CharField(blank=True, max_length=255)),
                ('percentage', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
        migrations.DeleteModel(
            name='MySkills',
        ),
    ]
