# Generated by Django 2.1.2 on 2018-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataskill', models.CharField(blank=True, max_length=255)),
                ('percentage', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myskills', models.TextField()),
            ],
        ),
    ]
